# 免费邮箱API
mail:
  api: api

# 请求
requests:
  # 超时设置
  out_time: 120
  # 重试次数
  retry: 10

invites:
  - mail: wiwaret166@talmetry.com
    invite_number: 95370395
  - mail: lopipi9801@giratex.com
    invite_number: 39576161
  - mail: weyel44478@namewok.com
    invite_number: 92196679
  - mail: himiren433@picvw.com
    invite_number: 85147854
  - mail: vepahe1532@roborena.com
    invite_number: 74553676