# 免费邮箱API
mail:
  api: API

twocaptcha:
  api: API

# 默认的密码
def_password: 098poi

# 请求
requests:
  # 超时设置
  out_time: 120
  # 重试次数
  retry: 3

alist:
  enable: 0
  domain: "http://localhost:5244"
  # domain: "http:// 10.211.55.2:5244"
  username: admin
  password: "''''"

rclone:
  mount_root: /mnt/pikpak

telegram:
  api: API

# 替换模式 为 all 全部替换。。 randam 一个新好替换下一个不是vip的账户。。 none 全部都是邀请不进行替换
invate_change_model: randam
